import type { GetStaticProps } from 'next';
import Head from 'next/head';
import { Container, Typography } from '@mui/material';
import { mapPageToTimelineItem, Page, TimelineItem } from '../types/api';
import CustomTimeline from '../components/timeline';

interface IndexProps {
  timelineItems: TimelineItem[];
}

const Index = ({ timelineItems }: IndexProps) => {
  return (
    <div>
      <Head>
        <title>Timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ mt: 4 }}>
        <Typography variant="h1">Timeline</Typography>
        <CustomTimeline items={timelineItems} />
        <pre>{JSON.stringify(timelineItems, null, 2)}</pre>
      </Container>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(`http://localhost:3000/api/timeline-pages`);
  const pages: Page[] = await res.json();

  if (!pages) {
    return {
      notFound: true,
    };
  }

  const timelineItems = pages.map(mapPageToTimelineItem);

  return {
    props: { timelineItems }, // will be passed to the page component as props
  };
};

export default Index;
